#!/bin/bash
source /home/mort/venv38/bin/activate
cd src
cd ~/python/eeimad/src
python setup.py install
python setup.py sdist
jupyter notebook --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token=''
